package kiarusitas;

public class kiarusitas extends javax.swing.JFrame {

    int poloAlapAr = 1;
    int db = 1;
    int szinek;
    double vegsoAr;
    double meret;
    int szin1;
    int szin2;
    int szin3;
    int szin4;
    int szin5;
    String osszegzes1 = "Válaszd ki, hogy milyen póló neműt szeretnél!";
    int osszegzes2;
    String osszegzes3 = "Válaszd ki a póló méretét!";
    String szinek1;
    String szinek2;
    String szinek3;
    String szinek4;
    String szinek5;
    
    public kiarusitas() {
        initComponents();
        
        poloAlapAr = 0;
        
        meret = 1;
        
        szin1 = 0;
        szin2 = 0;
        szin3 = 0;
        szin4 = 0;
        szin5 = 0;
        szinek = szin1 + szin2 + szin3 + szin4 + szin5;
        
        db = 1;
        
        vegsoAr = poloAlapAr * meret + szinek;
        vegsoAr *= db;
        
        lblAr.setText(vegsoAr + "");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlhatter = new javax.swing.JPanel();
        pnlfejlec = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlnem = new javax.swing.JPanel();
        cmbValaszthatoNem = new javax.swing.JComboBox<>();
        pnldesigne1 = new javax.swing.JPanel();
        pnldesigne2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnldesigne3 = new javax.swing.JPanel();
        pnlMeret = new javax.swing.JPanel();
        rdbMeretS = new javax.swing.JRadioButton();
        rdbMeretM = new javax.swing.JRadioButton();
        rdbMeretL = new javax.swing.JRadioButton();
        rdbMeretX = new javax.swing.JRadioButton();
        rdbMeretXL = new javax.swing.JRadioButton();
        rdbMeretXXL = new javax.swing.JRadioButton();
        pnldesigne4 = new javax.swing.JPanel();
        pnldesigne5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlSzinek = new javax.swing.JPanel();
        chbFeher = new javax.swing.JCheckBox();
        chbFekete = new javax.swing.JCheckBox();
        chbSzurke = new javax.swing.JCheckBox();
        chbKek = new javax.swing.JCheckBox();
        chbPiros = new javax.swing.JCheckBox();
        pnldesigne6 = new javax.swing.JPanel();
        pnlFizetendo = new javax.swing.JPanel();
        lblAr = new javax.swing.JLabel();
        lblFizFt = new javax.swing.JLabel();
        lblFizDb = new javax.swing.JLabel();
        numDb = new javax.swing.JSpinner();
        btnRendel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaKosar = new javax.swing.JTextArea();
        lblKosarka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlhatter.setBackground(new java.awt.Color(255, 51, 51));
        pnlhatter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlfejlec.setBackground(new java.awt.Color(255, 102, 102));
        pnlfejlec.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kiárusítás - Színes Pólók");

        javax.swing.GroupLayout pnlfejlecLayout = new javax.swing.GroupLayout(pnlfejlec);
        pnlfejlec.setLayout(pnlfejlecLayout);
        pnlfejlecLayout.setHorizontalGroup(
            pnlfejlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfejlecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlfejlecLayout.setVerticalGroup(
            pnlfejlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfejlecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlnem.setBackground(new java.awt.Color(204, 0, 0));
        pnlnem.setBorder(javax.swing.BorderFactory.createTitledBorder("Milyen nemű pólót szeretnél?"));

        cmbValaszthatoNem.setBackground(new java.awt.Color(255, 102, 102));
        cmbValaszthatoNem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">>Válassz pólónemet<<", "Női pólók", "Férfi pólók" }));
        cmbValaszthatoNem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValaszthatoNemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlnemLayout = new javax.swing.GroupLayout(pnlnem);
        pnlnem.setLayout(pnlnemLayout);
        pnlnemLayout.setHorizontalGroup(
            pnlnemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbValaszthatoNem, 0, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlnemLayout.setVerticalGroup(
            pnlnemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbValaszthatoNem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnldesigne1.setBackground(new java.awt.Color(255, 0, 0));
        pnldesigne1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnldesigne1Layout = new javax.swing.GroupLayout(pnldesigne1);
        pnldesigne1.setLayout(pnldesigne1Layout);
        pnldesigne1Layout.setHorizontalGroup(
            pnldesigne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        pnldesigne1Layout.setVerticalGroup(
            pnldesigne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        pnldesigne2.setBackground(new java.awt.Color(255, 0, 0));
        pnldesigne2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabua\\OneDrive\\Asztali gép\\kiarusitas\\polo_piros.png")); // NOI18N

        javax.swing.GroupLayout pnldesigne2Layout = new javax.swing.GroupLayout(pnldesigne2);
        pnldesigne2.setLayout(pnldesigne2Layout);
        pnldesigne2Layout.setHorizontalGroup(
            pnldesigne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldesigne2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnldesigne2Layout.setVerticalGroup(
            pnldesigne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldesigne2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnldesigne3.setBackground(new java.awt.Color(255, 102, 102));
        pnldesigne3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnldesigne3Layout = new javax.swing.GroupLayout(pnldesigne3);
        pnldesigne3.setLayout(pnldesigne3Layout);
        pnldesigne3Layout.setHorizontalGroup(
            pnldesigne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        pnldesigne3Layout.setVerticalGroup(
            pnldesigne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnlMeret.setBackground(new java.awt.Color(204, 0, 51));
        pnlMeret.setBorder(javax.swing.BorderFactory.createTitledBorder("Méretek:"));

        buttonGroup1.add(rdbMeretS);
        rdbMeretS.setText("S");
        rdbMeretS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMeretSItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMeretM);
        rdbMeretM.setText("M");
        rdbMeretM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMeretMItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMeretL);
        rdbMeretL.setText("L");
        rdbMeretL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMeretLItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMeretX);
        rdbMeretX.setText("X");
        rdbMeretX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMeretXItemStateChanged(evt);
            }
        });
        rdbMeretX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMeretXActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbMeretXL);
        rdbMeretXL.setText("XL");
        rdbMeretXL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMeretXLItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMeretXXL);
        rdbMeretXXL.setText("XXL");
        rdbMeretXXL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMeretXXLItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlMeretLayout = new javax.swing.GroupLayout(pnlMeret);
        pnlMeret.setLayout(pnlMeretLayout);
        pnlMeretLayout.setHorizontalGroup(
            pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeretLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMeretLayout.createSequentialGroup()
                        .addComponent(rdbMeretS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbMeretM))
                    .addGroup(pnlMeretLayout.createSequentialGroup()
                        .addComponent(rdbMeretX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbMeretXL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbMeretXXL)
                    .addComponent(rdbMeretL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMeretLayout.setVerticalGroup(
            pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeretLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMeretS)
                    .addComponent(rdbMeretM)
                    .addComponent(rdbMeretL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMeretX)
                    .addComponent(rdbMeretXL)
                    .addComponent(rdbMeretXXL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnldesigne4.setBackground(new java.awt.Color(255, 153, 153));
        pnldesigne4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnldesigne4Layout = new javax.swing.GroupLayout(pnldesigne4);
        pnldesigne4.setLayout(pnldesigne4Layout);
        pnldesigne4Layout.setHorizontalGroup(
            pnldesigne4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        pnldesigne4Layout.setVerticalGroup(
            pnldesigne4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        pnldesigne5.setBackground(new java.awt.Color(255, 0, 0));
        pnldesigne5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabua\\OneDrive\\Asztali gép\\kiarusitas\\polo_kek.png")); // NOI18N

        javax.swing.GroupLayout pnldesigne5Layout = new javax.swing.GroupLayout(pnldesigne5);
        pnldesigne5.setLayout(pnldesigne5Layout);
        pnldesigne5Layout.setHorizontalGroup(
            pnldesigne5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldesigne5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnldesigne5Layout.setVerticalGroup(
            pnldesigne5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldesigne5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pnlSzinek.setBackground(new java.awt.Color(204, 0, 0));
        pnlSzinek.setBorder(javax.swing.BorderFactory.createTitledBorder("Színek:"));

        chbFeher.setText("Fehér");
        chbFeher.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbFeherStateChanged(evt);
            }
        });

        chbFekete.setText("Fekete");
        chbFekete.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbFeketeStateChanged(evt);
            }
        });
        chbFekete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFeketeActionPerformed(evt);
            }
        });

        chbSzurke.setText("Szürke");
        chbSzurke.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbSzurkeStateChanged(evt);
            }
        });

        chbKek.setText("Kék");
        chbKek.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbKekStateChanged(evt);
            }
        });

        chbPiros.setText("Piros");
        chbPiros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbPirosStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlSzinekLayout = new javax.swing.GroupLayout(pnlSzinek);
        pnlSzinek.setLayout(pnlSzinekLayout);
        pnlSzinekLayout.setHorizontalGroup(
            pnlSzinekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSzinekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSzinekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbFeher)
                    .addGroup(pnlSzinekLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(chbKek)))
                .addGap(18, 18, 18)
                .addGroup(pnlSzinekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSzinekLayout.createSequentialGroup()
                        .addComponent(chbFekete)
                        .addGap(18, 18, 18)
                        .addComponent(chbSzurke))
                    .addGroup(pnlSzinekLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(chbPiros)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlSzinekLayout.setVerticalGroup(
            pnlSzinekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSzinekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSzinekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbFeher)
                    .addComponent(chbFekete)
                    .addComponent(chbSzurke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSzinekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbKek)
                    .addComponent(chbPiros))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnldesigne6.setBackground(new java.awt.Color(255, 153, 204));
        pnldesigne6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnldesigne6Layout = new javax.swing.GroupLayout(pnldesigne6);
        pnldesigne6.setLayout(pnldesigne6Layout);
        pnldesigne6Layout.setHorizontalGroup(
            pnldesigne6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        pnldesigne6Layout.setVerticalGroup(
            pnldesigne6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnlFizetendo.setBackground(new java.awt.Color(255, 51, 102));
        pnlFizetendo.setBorder(javax.swing.BorderFactory.createTitledBorder("Fizetendő:"));

        lblAr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAr.setText("0");

        lblFizFt.setText("Ft");

        lblFizDb.setText("db:");

        numDb.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        numDb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numDbStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlFizetendoLayout = new javax.swing.GroupLayout(pnlFizetendo);
        pnlFizetendo.setLayout(pnlFizetendoLayout);
        pnlFizetendoLayout.setHorizontalGroup(
            pnlFizetendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetendoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFizetendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFizetendoLayout.createSequentialGroup()
                        .addComponent(lblAr, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFizFt))
                    .addGroup(pnlFizetendoLayout.createSequentialGroup()
                        .addComponent(lblFizDb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlFizetendoLayout.setVerticalGroup(
            pnlFizetendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetendoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFizetendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAr)
                    .addComponent(lblFizFt))
                .addGap(18, 18, 18)
                .addGroup(pnlFizetendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFizDb)
                    .addComponent(numDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRendel.setBackground(new java.awt.Color(255, 153, 153));
        btnRendel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRendel.setText("Megrendelem");
        btnRendel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendelActionPerformed(evt);
            }
        });

        txaKosar.setColumns(20);
        txaKosar.setRows(5);
        jScrollPane1.setViewportView(txaKosar);

        lblKosarka.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblKosarka.setText("Kosár:");

        javax.swing.GroupLayout pnlhatterLayout = new javax.swing.GroupLayout(pnlhatter);
        pnlhatter.setLayout(pnlhatterLayout);
        pnlhatterLayout.setHorizontalGroup(
            pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhatterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhatterLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(pnlhatterLayout.createSequentialGroup()
                        .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlfejlec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlhatterLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                                .addComponent(pnldesigne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhatterLayout.createSequentialGroup()
                                .addComponent(pnlnem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnldesigne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(pnldesigne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlhatterLayout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlFizetendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlhatterLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblKosarka)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlSzinek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlhatterLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnRendel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(pnlhatterLayout.createSequentialGroup()
                                .addComponent(pnldesigne5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnldesigne6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addContainerGap())
                    .addGroup(pnlhatterLayout.createSequentialGroup()
                        .addComponent(pnldesigne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(163, Short.MAX_VALUE))))
        );
        pnlhatterLayout.setVerticalGroup(
            pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhatterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlfejlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnldesigne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlhatterLayout.createSequentialGroup()
                        .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnldesigne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlnem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlhatterLayout.createSequentialGroup()
                                .addGroup(pnlhatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnldesigne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(pnldesigne6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlSzinek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRendel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlhatterLayout.createSequentialGroup()
                                .addComponent(pnldesigne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnldesigne5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFizetendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKosarka)))))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbFeketeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFeketeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFeketeActionPerformed

    private void cmbValaszthatoNemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValaszthatoNemActionPerformed
        
        int poloIndex = cmbValaszthatoNem.getSelectedIndex();
        
        if(poloIndex == 0){
            poloAlapAr = 1500;
            osszegzes1 = "A választott Pólónemű: Női";
        }else if(poloIndex == 1){
            poloAlapAr = 1500;
            osszegzes1 = "A választott Pólónemű: Férfi";
        }
        
        szamitasEsKiiras();
    }//GEN-LAST:event_cmbValaszthatoNemActionPerformed

    private void rdbMeretSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMeretSItemStateChanged
        meret = .75;
        osszegzes3 = "Választott méret: S";
        
        szamitasEsKiiras();
    }//GEN-LAST:event_rdbMeretSItemStateChanged

    private void rdbMeretMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMeretMItemStateChanged
        meret = 1.50;
        osszegzes3 = "Választott méret: M";
        
        szamitasEsKiiras();
    }//GEN-LAST:event_rdbMeretMItemStateChanged

    private void rdbMeretLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMeretLItemStateChanged
        meret = 2.25;
        osszegzes3 = "Választott méret: L";
        
        szamitasEsKiiras();
    }//GEN-LAST:event_rdbMeretLItemStateChanged

    private void rdbMeretXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMeretXItemStateChanged
        meret = 3;
        osszegzes3 = "Választott méret: X";
        
        szamitasEsKiiras();
    }//GEN-LAST:event_rdbMeretXItemStateChanged

    private void rdbMeretXLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMeretXLItemStateChanged
        meret = 3.75;
        osszegzes3 = "Választott méret: XL";
        
        szamitasEsKiiras();
    }//GEN-LAST:event_rdbMeretXLItemStateChanged

    private void rdbMeretXXLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMeretXXLItemStateChanged
        meret = 4.50;
        osszegzes3 = "Választott méret: XXL";
        
        szamitasEsKiiras();
    }//GEN-LAST:event_rdbMeretXXLItemStateChanged

    private void chbFeherStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbFeherStateChanged
        if(chbFeher.isSelected() == true)
        {
            szin1 = 1000;
        }else{
            szin1 = 0;
        }
        
        szamitasEsKiiras();
    }//GEN-LAST:event_chbFeherStateChanged

    private void chbFeketeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbFeketeStateChanged
        if(chbFekete.isSelected() == true)
        {
            szin2 = 1000;
        }else{
            szin2 = 0;
        }
        
        szamitasEsKiiras();
    }//GEN-LAST:event_chbFeketeStateChanged

    private void chbSzurkeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbSzurkeStateChanged
        if(chbSzurke.isSelected() == true)
        {
            szin3 = 1000;
        }else{
            szin3 = 0;
        }
        
        szamitasEsKiiras();
    }//GEN-LAST:event_chbSzurkeStateChanged

    private void chbKekStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbKekStateChanged
        if(chbKek.isSelected() == true)
        {
            szin4 = 1000;
        }else{
            szin4 = 0;
        }
        
        szamitasEsKiiras();
    }//GEN-LAST:event_chbKekStateChanged

    private void chbPirosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbPirosStateChanged
        if(chbPiros.isSelected() == true)
        {
            szin5 = 1000;
        }else{
            szin5 = 0;
        }
        
        szamitasEsKiiras();
    }//GEN-LAST:event_chbPirosStateChanged

    private void numDbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numDbStateChanged
        db = (int) numDb.getValue();
        
        szamitasEsKiiras();
    }//GEN-LAST:event_numDbStateChanged

    private void btnRendelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendelActionPerformed
        if(chbFeher.isSelected() == true)
        {
            szinek1 = "- Fehér";
        }else{
            szinek1 = "";
        }
        if(chbFekete.isSelected() == true)
        {
            szinek2 = "- Fekete";
        }else{
            szinek2 = "";
        }
        if(chbSzurke.isSelected() == true)
        {
            szinek3 = "- Szürke";
        }else{
            szinek3 = "";
        }
        if(chbKek.isSelected() == true)
        {
            szinek4 = "- Kék";
        }else{
            szinek4 = "";
        }
        if(chbPiros.isSelected() == true)
        {
            szinek5 = "- Piros";
        }else{
            szinek5 = "";
        }
        
        txaKosar.setText(osszegzes1 + " (" + db + "db)" + "\n" + osszegzes3 + "\n" + "Választott szín:" + "\n" + szinek1 + "\n" + szinek2 + "\n" + szinek3 + "\n" + szinek4 + "\n" + szinek5);
    }//GEN-LAST:event_btnRendelActionPerformed

    private void rdbMeretXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMeretXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMeretXActionPerformed

    private void szamitasEsKiiras() {
        vegsoAr = poloAlapAr * meret + szin1 + szin2 + szin3 + szin4 + szin5;
        vegsoAr *= db;
        
        lblAr.setText(vegsoAr + "");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kiarusitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kiarusitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kiarusitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kiarusitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kiarusitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRendel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbFeher;
    private javax.swing.JCheckBox chbFekete;
    private javax.swing.JCheckBox chbKek;
    private javax.swing.JCheckBox chbPiros;
    private javax.swing.JCheckBox chbSzurke;
    private javax.swing.JComboBox<String> cmbValaszthatoNem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAr;
    private javax.swing.JLabel lblFizDb;
    private javax.swing.JLabel lblFizFt;
    private javax.swing.JLabel lblKosarka;
    private javax.swing.JSpinner numDb;
    private javax.swing.JPanel pnlFizetendo;
    private javax.swing.JPanel pnlMeret;
    private javax.swing.JPanel pnlSzinek;
    private javax.swing.JPanel pnldesigne1;
    private javax.swing.JPanel pnldesigne2;
    private javax.swing.JPanel pnldesigne3;
    private javax.swing.JPanel pnldesigne4;
    private javax.swing.JPanel pnldesigne5;
    private javax.swing.JPanel pnldesigne6;
    private javax.swing.JPanel pnlfejlec;
    private javax.swing.JPanel pnlhatter;
    private javax.swing.JPanel pnlnem;
    private javax.swing.JRadioButton rdbMeretL;
    private javax.swing.JRadioButton rdbMeretM;
    private javax.swing.JRadioButton rdbMeretS;
    private javax.swing.JRadioButton rdbMeretX;
    private javax.swing.JRadioButton rdbMeretXL;
    private javax.swing.JRadioButton rdbMeretXXL;
    private javax.swing.JTextArea txaKosar;
    // End of variables declaration//GEN-END:variables
}
